/**
 * 実在するコンビニ・外食チェーンのメニューデータ
 * ※公表されている事実情報（商品名・カロリー・PFC・推定税込価格）
 * 画像無断転載を避け、視覚的で親しみやすいアイコンとタグで構成
 */

const MEAL_DATABASE = [
  // ==================== 朝食向け（セブン・ローソン・ファミマ・自炊軽食） ====================
  {
    id: "b_seven_1",
    name: "梅こんぶおむすび",
    store: "seven",
    storeName: "セブン",
    slot: "breakfast",
    calories: 168,
    p: 3.2,
    f: 0.8,
    c: 37.1,
    price: 130,
    icon: "🍙",
    tags: ["salty", "budget", "staple"]
  },
  {
    id: "b_seven_2",
    name: "味付き半熟ゆでたまご (1個)",
    store: "seven",
    storeName: "セブン",
    slot: "breakfast",
    calories: 65,
    p: 6.0,
    f: 4.4,
    c: 0.6,
    price: 105,
    icon: "🥚",
    tags: ["high_protein", "budget"]
  },
  {
    id: "b_seven_3",
    name: "とうふとわかめのおみそ汁",
    store: "seven",
    storeName: "セブン",
    slot: "breakfast",
    calories: 42,
    p: 2.8,
    f: 1.2,
    c: 4.9,
    price: 118,
    icon: "🥣",
    tags: ["soup", "budget", "warm"]
  },
  {
    id: "b_lawson_1",
    name: "NL ブランパン 2個入 (乳酸菌入)",
    store: "lawson",
    storeName: "ローソン",
    slot: "breakfast",
    calories: 134,
    p: 11.4,
    f: 5.4,
    c: 4.4,
    price: 149,
    icon: "🥖",
    tags: ["low_carb", "high_protein", "staple"]
  },
  {
    id: "b_lawson_2",
    name: "オイコス プレーン 砂糖不使用",
    store: "lawson",
    storeName: "ローソン",
    slot: "breakfast",
    calories: 71,
    p: 10.1,
    f: 0,
    c: 5.2,
    price: 198,
    icon: "🍶",
    tags: ["sweet", "high_protein", "clean"]
  },
  {
    id: "b_family_1",
    name: "直火焼き焼鮭おむすび",
    store: "family",
    storeName: "ファミマ",
    slot: "breakfast",
    calories: 182,
    p: 5.5,
    f: 1.8,
    c: 35.8,
    price: 168,
    icon: "🍙",
    tags: ["staple", "fish"]
  },
  {
    id: "b_family_2",
    name: "たんぱく質が摂れる！サラダチキンバー スモーク",
    store: "family",
    storeName: "ファミマ",
    slot: "breakfast",
    calories: 83,
    p: 14.5,
    f: 1.5,
    c: 2.8,
    price: 178,
    icon: "🍗",
    tags: ["high_protein", "salty", "meat"]
  },
  {
    id: "b_home_1",
    name: "バナナ1本 ＆ 納豆1パック (自宅軽食)",
    store: "home",
    storeName: "自宅軽食",
    slot: "breakfast",
    calories: 186,
    p: 8.5,
    f: 4.8,
    c: 32.0,
    price: 80,
    icon: "🍌",
    tags: ["budget", "clean", "healthy"]
  },

  // ==================== 昼食向け（コンビニ & 松屋・すき家・大戸屋） ====================
  {
    id: "l_seven_1",
    name: "たんぱく質が摂れる チキン＆チリ ロールパン",
    store: "seven",
    storeName: "セブン",
    slot: "lunch",
    calories: 298,
    p: 26.2,
    f: 9.8,
    c: 25.1,
    price: 399,
    icon: "🥪",
    tags: ["high_protein", "staple", "meat"]
  },
  {
    id: "l_seven_2",
    name: "豚しゃぶと根菜の胡麻サラダ",
    store: "seven",
    storeName: "セブン",
    slot: "lunch",
    calories: 162,
    p: 9.5,
    f: 8.2,
    c: 12.0,
    price: 430,
    icon: "🥗",
    tags: ["veggie", "meat"]
  },
  {
    id: "l_lawson_1",
    name: "たんぱく質が摂れる 蒸し鶏と玉子のサラダ",
    store: "lawson",
    storeName: "ローソン",
    slot: "lunch",
    calories: 185,
    p: 20.1,
    f: 9.2,
    c: 5.4,
    price: 497,
    icon: "🥗",
    tags: ["high_protein", "veggie"]
  },
  {
    id: "l_lawson_2",
    name: "もち麦入り 枝豆と塩昆布おにぎり",
    store: "lawson",
    storeName: "ローソン",
    slot: "lunch",
    calories: 172,
    p: 4.8,
    f: 1.9,
    c: 33.5,
    price: 140,
    icon: "🍙",
    tags: ["salty", "budget", "staple"]
  },
  {
    id: "l_family_1",
    name: "全粒粉サンド サラダチキンとたまご",
    store: "family",
    storeName: "ファミマ",
    slot: "lunch",
    calories: 312,
    p: 22.4,
    f: 11.5,
    c: 28.6,
    price: 350,
    icon: "🥪",
    tags: ["high_protein", "staple"]
  },
  {
    id: "l_matsuya_1",
    name: "牛焼肉定食（ライス小盛・生野菜＋ポン酢）",
    store: "matsuya",
    storeName: "松屋",
    slot: "lunch",
    calories: 610,
    p: 29.5,
    f: 22.0,
    c: 72.0,
    price: 790,
    icon: "🥩",
    tags: ["meat", "gourmet", "high_protein"]
  },
  {
    id: "l_sukiya_1",
    name: "牛丼ライト（ご飯の代わりに豆腐使用）並盛",
    store: "sukiya",
    storeName: "すき家",
    slot: "lunch",
    calories: 425,
    p: 25.1,
    f: 27.5,
    c: 17.9,
    price: 530,
    icon: "🍲",
    tags: ["low_carb", "meat", "high_protein"]
  },
  {
    id: "l_ootoya_1",
    name: "すけそう鱈と野菜の黒酢あん定食（五穀ご飯少なめ）",
    store: "ootoya",
    storeName: "大戸屋",
    slot: "lunch",
    calories: 590,
    p: 21.0,
    f: 15.0,
    c: 91.0,
    price: 990,
    icon: "🍱",
    tags: ["fish", "veggie", "healthy"]
  },

  // ==================== 夕食向け（夜軽め or 外食定食・コンビニ鍋・スープ） ====================
  {
    id: "d_seven_1",
    name: "1/2日分の野菜！キムチ鍋（豆腐・豚肉入り）",
    store: "seven",
    storeName: "セブン",
    slot: "dinner",
    calories: 278,
    p: 21.8,
    f: 11.4,
    c: 18.2,
    price: 572,
    icon: "🍲",
    tags: ["spicy", "high_protein", "warm", "veggie"]
  },
  {
    id: "d_seven_2",
    name: "銀鮭の塩焼き",
    store: "seven",
    storeName: "セブン",
    slot: "dinner",
    calories: 198,
    p: 18.5,
    f: 13.5,
    c: 0.2,
    price: 368,
    icon: "🐟",
    tags: ["fish", "high_protein", "salty"]
  },
  {
    id: "d_lawson_1",
    name: "国産サラダチキン プレーン ＆ 海藻と大根のサラダ",
    store: "lawson",
    storeName: "ローソン",
    slot: "dinner",
    calories: 165,
    p: 26.5,
    f: 2.5,
    c: 6.8,
    price: 490,
    icon: "🥗",
    tags: ["high_protein", "budget", "clean"]
  },
  {
    id: "d_ootoya_2",
    name: "しまほっけの炭火焼き定食（五穀ご飯少なめ）",
    store: "ootoya",
    storeName: "大戸屋",
    slot: "dinner",
    calories: 540,
    p: 38.0,
    f: 12.0,
    c: 68.0,
    price: 1050,
    icon: "🐟",
    tags: ["fish", "high_protein", "healthy"]
  },
  {
    id: "d_yoshinoya_1",
    name: "牛鮭定食（ご飯少なめ）",
    store: "yoshinoya",
    storeName: "吉野家",
    slot: "dinner",
    calories: 630,
    p: 31.0,
    f: 22.0,
    c: 75.0,
    price: 745,
    icon: "🥩",
    tags: ["meat", "fish", "high_protein"]
  },

  // ==================== 間食・スイーツ枠（甘いもの / しょっぱいもの） ====================
  {
    id: "s_sweet_1",
    name: "SUNAO バニラアイス（糖質50%オフ）",
    store: "lawson",
    storeName: "ローソン/コンビニ",
    slot: "snack",
    calories: 80,
    p: 2.4,
    f: 4.1,
    c: 9.3,
    price: 180,
    icon: "🍨",
    tags: ["sweet", "snack"]
  },
  {
    id: "s_sweet_2",
    name: "糖質70%オフ チョコチップスコーン",
    store: "seven",
    storeName: "セブン",
    slot: "snack",
    calories: 145,
    p: 4.5,
    f: 7.2,
    c: 13.0,
    price: 170,
    icon: "🍪",
    tags: ["sweet", "chocolate", "snack"]
  },
  {
    id: "s_sweet_3",
    name: "寒天ゼリー ゼロカロリー ぶどう味",
    store: "family",
    storeName: "ファミマ",
    slot: "snack",
    calories: 0,
    p: 0,
    f: 0,
    c: 0.5,
    price: 120,
    icon: "🍇",
    tags: ["sweet", "zero_cal", "budget", "snack"]
  },
  {
    id: "s_salty_1",
    name: "やわらかスモーク豚タン",
    store: "seven",
    storeName: "セブン",
    slot: "snack",
    calories: 104,
    p: 13.2,
    f: 5.6,
    c: 0.5,
    price: 246,
    icon: "🥓",
    tags: ["salty", "high_protein", "snack"]
  },
  {
    id: "s_salty_2",
    name: "三陸産くきわかめ (梅しそ味)",
    store: "seven",
    storeName: "セブン/ファミマ",
    slot: "snack",
    calories: 28,
    p: 0.8,
    f: 0.1,
    c: 5.8,
    price: 140,
    icon: "🌿",
    tags: ["salty", "budget", "low_cal", "snack"]
  },
  {
    id: "s_salty_3",
    name: "パリパリ食感のこんにゃくチップス のり塩味",
    store: "lawson",
    storeName: "ローソン",
    slot: "snack",
    calories: 61,
    p: 0.2,
    f: 2.1,
    c: 9.8,
    price: 168,
    icon: "🥔",
    tags: ["salty", "low_cal", "snack"]
  },

  // ==================== ドリンク・カフェ枠 ====================
  {
    id: "dr_starbucks_1",
    name: "スターバックス カフェアメリカーノ (Short/無脂肪乳)",
    store: "starbucks",
    storeName: "スタバ",
    slot: "drink",
    calories: 11,
    p: 0.7,
    f: 0.1,
    c: 1.8,
    price: 430,
    icon: "☕",
    tags: ["drink", "cafe", "low_cal"]
  },
  {
    id: "dr_starbucks_2",
    name: "スターバックス ソイラテ (Tall/ホット/無糖シロップ)",
    store: "starbucks",
    storeName: "スタバ",
    slot: "drink",
    calories: 191,
    p: 10.2,
    f: 9.8,
    c: 14.1,
    price: 520,
    icon: "☕",
    tags: ["drink", "cafe", "high_protein"]
  },
  {
    id: "dr_seven_1",
    name: "セブンカフェ アイスカフェラテ (R/無糖)",
    store: "seven",
    storeName: "セブンカフェ",
    slot: "drink",
    calories: 78,
    p: 4.1,
    f: 4.2,
    c: 5.9,
    price: 240,
    icon: "🧊☕",
    tags: ["drink", "cafe", "budget"]
  },
  {
    id: "dr_seven_2",
    name: "サントリー 伊右衛門 特茶（特定保健用食品）500ml",
    store: "seven",
    storeName: "コンビニ各社",
    slot: "drink",
    calories: 0,
    p: 0,
    f: 0,
    c: 0,
    price: 190,
    icon: "🍵",
    tags: ["drink", "zero_cal", "healthy"]
  },
  {
    id: "dr_seven_3",
    name: "ペプシスペシャル ゼロ 490ml",
    store: "all",
    storeName: "コンビニ各社",
    slot: "drink",
    calories: 0,
    p: 0,
    f: 0,
    c: 0,
    price: 170,
    icon: "🥤",
    tags: ["drink", "sweet", "zero_cal"]
  },
  // ==================== 一般的な家庭料理・定番主食・フルーツ ====================
  { id: "h_rice", name: "白ご飯 (茶碗1杯 150g)", store: "home", storeName: "主食", slot: "breakfast", calories: 234, p: 3.8, f: 0.5, c: 53.4, price: 50, icon: "🍚", tags: ["staple", "home"] },
  { id: "h_toast", name: "食パン (6枚切 1枚 バター付)", store: "home", storeName: "主食", slot: "breakfast", calories: 210, p: 5.5, f: 6.8, c: 31.0, price: 40, icon: "🍞", tags: ["staple", "bread"] },
  { id: "h_egg_fried", name: "目玉焼き (1個)", store: "home", storeName: "家庭料理", slot: "breakfast", calories: 95, p: 6.5, f: 7.2, c: 0.2, price: 30, icon: "🍳", tags: ["high_protein", "egg"] },
  { id: "h_tamagoyaki", name: "卵焼き (2切れ)", store: "home", storeName: "家庭料理", slot: "breakfast", calories: 145, p: 8.2, f: 9.8, c: 4.5, price: 60, icon: "🥚", tags: ["high_protein", "egg"] },
  { id: "h_natto", name: "納豆 (1パック タレ・からし付)", store: "home", storeName: "家庭料理", slot: "breakfast", calories: 86, p: 7.4, f: 4.4, c: 5.4, price: 35, icon: "🥢", tags: ["healthy", "high_protein"] },
  { id: "h_miso", name: "豆腐とわかめの味噌汁 (1杯)", store: "home", storeName: "家庭料理", slot: "breakfast", calories: 55, p: 3.8, f: 1.8, c: 5.2, price: 40, icon: "🥣", tags: ["soup", "healthy"] },
  { id: "h_banana", name: "バナナ (1本 中サイズ)", store: "fresh", storeName: "果物", slot: "snack", calories: 86, p: 1.1, f: 0.2, c: 22.5, price: 50, icon: "🍌", tags: ["fruit", "healthy"] },
  { id: "h_apple", name: "りんご (1/2個)", store: "fresh", storeName: "果物", slot: "snack", calories: 70, p: 0.3, f: 0.2, c: 18.0, price: 80, icon: "🍎", tags: ["fruit", "healthy"] },
  { id: "h_milk", name: "牛乳 (コップ1杯 200ml)", store: "home", storeName: "飲料", slot: "breakfast", calories: 134, p: 6.6, f: 7.6, c: 9.6, price: 55, icon: "🥛", tags: ["drink", "high_protein"] },
  { id: "h_curry", name: "チキンカレーライス (普通盛り)", store: "home", storeName: "家庭料理", slot: "lunch", calories: 680, p: 18.5, f: 20.0, c: 105.0, price: 350, icon: "🍛", tags: ["staple", "curry"] },
  { id: "h_hamburg", name: "デミグラスハンバーグ (付け合わせ付)", store: "home", storeName: "家庭料理", slot: "dinner", calories: 480, p: 26.0, f: 28.5, c: 24.0, price: 300, icon: "🥩", tags: ["high_protein", "meat"] },
  { id: "h_karaage", name: "鶏のからあげ (4個)", store: "home", storeName: "家庭料理", slot: "dinner", calories: 340, p: 22.0, f: 22.0, c: 11.0, price: 200, icon: "🍗", tags: ["high_protein", "fried"] },
  { id: "h_salmon", name: "焼き鮭・塩鮭 (1切れ)", store: "home", storeName: "家庭料理", slot: "breakfast", calories: 195, p: 22.4, f: 11.0, c: 0.1, price: 180, icon: "🐟", tags: ["high_protein", "fish"] },
  { id: "h_udon", name: "かけうどん (ねぎ・かまぼこ)", store: "home", storeName: "麺類", slot: "lunch", calories: 320, p: 8.5, f: 2.0, c: 65.0, price: 150, icon: "🍜", tags: ["noodle", "staple"] },
  { id: "h_ramen", name: "醤油ラーメン (チャーシュー・メンマ)", store: "home", storeName: "麺類", slot: "lunch", calories: 520, p: 21.0, f: 16.5, c: 72.0, price: 400, icon: "🍜", tags: ["noodle", "soup"] },
  { id: "h_pasta", name: "ミートソースパスタ (普通盛り)", store: "home", storeName: "麺類", slot: "lunch", calories: 590, p: 21.5, f: 18.0, c: 84.0, price: 250, icon: "🍝", tags: ["noodle", "pasta"] },
  { id: "h_gyudon", name: "牛丼 (並盛り つゆ普通)", store: "home", storeName: "外食", slot: "lunch", calories: 650, p: 20.0, f: 23.0, c: 88.0, price: 480, icon: "🍚", tags: ["meat", "staple"] },
  { id: "h_tonkatsu", name: "とんかつ・ロースカツ (1枚)", store: "home", storeName: "家庭料理", slot: "dinner", calories: 460, p: 24.0, f: 34.0, c: 12.0, price: 320, icon: "🍱", tags: ["meat", "fried"] },
  { id: "h_sandwich", name: "ミックスサンド (ハム・たまご・レタス)", store: "seven", storeName: "コンビニ", slot: "breakfast", calories: 285, p: 10.2, f: 13.5, c: 29.5, price: 280, icon: "🥪", tags: ["bread", "staple"] },
  { id: "h_salad_chicken", name: "国産鶏サラダチキン プレーン", store: "all", storeName: "コンビニ", slot: "lunch", calories: 115, p: 24.5, f: 1.2, c: 0.5, price: 230, icon: "🥗", tags: ["high_protein", "clean"] },
  { id: "h_protein_bar", name: "プロテインバー (チョコ味)", store: "all", storeName: "間食", slot: "snack", calories: 195, p: 15.0, f: 9.5, c: 12.5, price: 160, icon: "🍫", tags: ["snack", "high_protein"] }
];
